# 1. 베이스 이미지 선택
FROM node:20-alpine

# 2. 작업 디렉토리 설정 및 소스 코드 복사
WORKDIR /app
COPY . .

# 3. 의존성 설치
RUN npm install

# 4. 애플리케이션 빌드
RUN npm run build

# 5. Docker 이미지 설정
EXPOSE 3000
CMD ["npm", "start"]


FROM nginx:stable-alpine as production-stage
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
